"""rename file_path to blob_url in medical_records

Revision ID: 0610863fea89
Revises: 4555f8cc7f1c
Create Date: 2026-06-02 14:56:11.878950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0610863fea89'
down_revision: Union[str, Sequence[str], None] = '4555f8cc7f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('record_id', sa.String(length=10), nullable=False))
    op.add_column('medical_records', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('medical_records', sa.Column('blob_url', sa.String(length=2000), nullable=False))
    op.add_column('medical_records', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('medical_records', sa.Column('size_kb', sa.Float(), nullable=False))
    op.add_column('medical_records', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'medical_records', ['record_id'])
    op.drop_constraint(op.f('medical_records_doctor_id_fkey'), 'medical_records', type_='foreignkey')
    op.drop_column('medical_records', 'prescription')
    op.drop_column('medical_records', 'doctor_id')
    op.drop_column('medical_records', 'notes')
    op.drop_column('medical_records', 'diagnosis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('diagnosis', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('medical_records', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('medical_records', sa.Column('prescription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('medical_records_doctor_id_fkey'), 'medical_records', 'doctors', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'medical_records', type_='unique')
    op.drop_column('medical_records', 'uploaded_at')
    op.drop_column('medical_records', 'size_kb')
    op.drop_column('medical_records', 'file_type')
    op.drop_column('medical_records', 'blob_url')
    op.drop_column('medical_records', 'filename')
    op.drop_column('medical_records', 'record_id')
    # ### end Alembic commands ###
