"""create medical records table

Revision ID: 4555f8cc7f1c
Revises: 0db7625ca731
Create Date: 2026-05-25 12:32:41.964482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4555f8cc7f1c'
down_revision: Union[str, Sequence[str], None] = '0db7625ca731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('medical_records',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('record_id', sa.String(length=10), nullable=False),
    # sa.Column('patient_id', sa.String(length=10), nullable=False),
    # sa.Column('filename', sa.String(length=255), nullable=False),
    # sa.Column('file_path', sa.String(length=500), nullable=False),
    # sa.Column('file_type', sa.String(length=50), nullable=False),
    # sa.Column('size_kb', sa.Float(), nullable=False),
    # sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('record_id')
    # )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('medical_records')
    pass
    # ### end Alembic commands ###
